# Generated by Django 5.0.6 on 2026-04-27 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp_tracking', '0001_initial'),
    ]

    operations = [
    ]
