# Generated by Django 5.0.6 on 2026-04-27 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp_tracking', '0002_whatsapp_click'),
        ('whatsapp_tracking', '0002_whatsappclick'),
    ]

    operations = [
    ]
