# Generated by Django 5.0.6 on 2026-09-09 11:57

import apps.common.encryption
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pipeline', '0001_initial'),
        ('sales', '0003_merge_0002_add_pipeline_fk_0002_sale_customer_fields'),
        ('tenants', '0004_tenant_status_active_default'),
    ]

    operations = [
        migrations.CreateModel(
            name='KommoConnection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('subdomain', models.CharField(help_text="e.g. clientname.kommo.com — the tenant's own Kommo account", max_length=255)),
                ('access_token', apps.common.encryption.EncryptedTextField(default='')),
                ('token_expires_at', models.DateTimeField(blank=True, help_text='Optional — set if the tenant tells us the expiry they chose (1 day to 5 years)', null=True)),
                ('sync_enabled', models.BooleanField(default=True)),
                ('connected_at', models.DateTimeField(auto_now_add=True)),
                ('last_synced', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='kommo_connection', to='tenants.tenant')),
            ],
            options={
                'db_table': 'kommo_connections',
            },
        ),
        migrations.CreateModel(
            name='KommoMatchedLead',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kommo_lead_id', models.CharField(blank=True, db_index=True, default='', max_length=100)),
                ('status', models.CharField(choices=[('pending', 'Pending match'), ('matched', 'Matched'), ('won', 'Won — synced as sale'), ('lost', 'Lost'), ('unmatched', 'Could not match')], default='pending', max_length=20)),
                ('match_method', models.CharField(blank=True, choices=[('phone', 'Phone number (WhatsApp)'), ('time_window', 'Nearest in time (Messenger/Instagram)')], default='', max_length=20)),
                ('match_attempts', models.PositiveSmallIntegerField(default=0)),
                ('won_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('won_at', models.DateTimeField(blank=True, null=True)),
                ('raw_lead_data', models.JSONField(blank=True, default=dict)),
                ('matched_at', models.DateTimeField(blank=True, null=True)),
                ('last_checked', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pipeline_deal', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='kommo_match', to='pipeline.pipelinedeal')),
                ('sale', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kommo_matched_lead', to='sales.sale')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kommo_matched_leads', to='tenants.tenant')),
            ],
            options={
                'db_table': 'kommo_matched_leads',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['tenant', 'status'], name='kommo_match_tenant__4a30ca_idx'), models.Index(fields=['kommo_lead_id'], name='kommo_match_kommo_l_17f18d_idx')],
            },
        ),
    ]
