# Generated by Django 5.0.6 on 2026-09-10 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kommo_integration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='kommoconnection',
            name='pipeline_cache',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='kommoconnection',
            name='pipeline_cache_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='kommomatchedlead',
            name='kommo_pipeline_id',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='kommomatchedlead',
            name='kommo_status_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='kommomatchedlead',
            name='kommo_status_name',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
