# Generated by Django 5.0.6 on 2026-09-10 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kommo_integration', '0002_migration'),
    ]

    operations = [
        migrations.AddField(
            model_name='kommoconnection',
            name='funnel_counts_cache',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='kommoconnection',
            name='funnel_counts_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
