# Generated by Django 5.0.6 on 2026-04-16 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_add_pipeline_fk'),
        ('sales', '0002_sale_customer_fields'),
    ]

    operations = [
    ]
